//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCRUD.Business.Logic.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentRecord
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string RollNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ClassId { get; set; }
    
        public virtual tblClass tblClass { get; set; }
    }
}
